### PR TITLE
Continue of pull request on AsynIO 

### PR DESCRIPTION
**Pull request by Guy-Markman**
Second version

### CODE REVIEW

**Comment by Guy-Markman** [comment]
@alonbl
I've decided to switch the exce with rollback. It gives me also the line whice caused the problem

**Comment by alonbl** [comment]
I do not follow.

**Comment by Guy-Markman** [comment]
You asked me to merge my pull request on the AsynIO and creat a new one.
I did it and here are the changes I made.
The biggest one is probably that I switch the use of saving the exception and print it in the end to the use of traceback

**Comment by alonbl** [comment]
ok, but where is the new change?
all I see is this merge

**Comment by alonbl** [comment]
Anyway, not that important, please implement http advanced exercise from last year as async.

**Pull request merged**
